config/routes.rb
Rails.application.routes.draw do
  get 'posts/new' => 'posts#new'
  post 'posts/create' => 'posts#create'
  get 'posts/index' => 'posts#index'
  get 'posts/:id' => 'posts#show'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/destroy' => 'posts#destroy'

  get 'signup' => 'users#new'
  post 'users/create' => 'users#create'
  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'
  get 'users/index' => 'users#index'
  get '/users/search_result' => 'users#search'
  get 'users/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit'
  post 'users/:id/update' => 'users#update',as: :user_update
  get 'users/:id/likes' => 'users#likes'
  get 'users/:id/follows' => 'users#follows'
  
  post 'likes/:post_id/create' => 'likes#create'
  post 'likes/:post_id/destroy' => 'likes#destroy'
  
  post 'follows/:id/create' => 'follows#create',as: :follow_create
  post 'follows/:id/destroy' => 'follows#destroy',as: :follow_destroy

  get '/' => 'home#top'
  get 'about' => 'home#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    
  validates :content, {presence:true, length: {maximum:200}}
  
  
  def user
    return User.find_by(id: self.user_id)
  end
    
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, {presence:true, uniqueness:true}
  #validates :password, {length: {minimum: 6}}
  validates :password, presence: true,length: { minimum: 6 },on: :create
  validates :self_intro, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence:true, uniqueness:true, format: {with:VALID_EMAIL_REGEX}}
  has_secure_password validations: false
  
  def post
    return Post.find_by(user_id: self.id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_user

  def set_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    if session[:user_id] == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end
  
  def forbid_login_user
    if session[:user_id]
      flash[:notice] = "すでにログインしています"
      redirect_to("/posts/index")
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user

  def create 
    @follow = Follow.new(
      user_id: @current_user.id,
      followed_id: params[:id]
    )
    @follow.save
    redirect_to("/users/#{params[:id]}")
  end
  
  def destroy
    @follow = Follow.find_by(
      user_id: @current_user.id,
      followed_id: params[:id]
    )
    @follow.destroy
    redirect_to("/users/#{params[:id]}")
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user, {only: [:top]}

  def top
  end
  
  def about 
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user
  
  def create
    @like = Like.new(
      post_id: params[:post_id],
      user_id: @current_user.id
    )
    # DBに保存
    @like.save
    redirect_to("/posts/#{params[:post_id]}")
  end
  
  def destroy
    @like = Like.find_by(
      post_id: params[:post_id],
      user_id: @current_user.id
     )
    @like.destroy
    redirect_to("/posts/#{params[:post_id]}")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit,:update,:destroy]}

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @current_user.id != @post.user_id
      flash[:notice] = "アクセス権限がありません"
      redirect_to("/posts/index")
    end
  end

  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user.id)
    @likes_count = Like.where(post_id: params[:id]).count
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "投稿を編集しました"
      redirect_to("/posts/#{@post.id}")
    else
      render("posts/edit")
    end
  end
  
  def new
    @post = Post.new()
  end
  
  def create
    @post = Post.new(
      content: params[:content],
      user_id: @current_user.id
    )
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to("/posts/index")
    else 
      render("posts/new")
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to("/")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index,:show,:edit,:update,:logout,:likes,:follows]}
  before_action :forbid_login_user, {only: [:new,:create,:login_form,:login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}
  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "アクセス権限がありません"
      redirect_to("/posts\index")
    end
  end
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by(id: params[:id])
    @posts = Post.where(user_id: params[:id]).order(created_at: :desc)
    @follower_count = Follow.where(followed_id: params[:id]).count
    @follow_count = Follow.where(user_id: params[:id]).count
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]#params[:user][:name]
    @user.email = params[:email]#params[:user][:email]
    @user.self_intro = params[:self_intro]
    @user.image_name = "#{@user.id}.jpg"
    image = params[:image]
    if image
      File.binwrite("public/user_images/#{@user.image_name}",image.read)
    end
    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end
  
  def likes 
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: params[:id]).order(created_at: :desc)
    @follower_count = Follow.where(followed_id: params[:id]).count
    @follow_count = Follow.where(user_id: params[:id]).count
  end
  
  def follows
    @user = User.find_by(id: params[:id])
    @follows = Follow.where(user_id: @user.id)
    @follows.each do |follow|
      @posts = Post.where(user_id: follow.followed_id).order(created_at: :desc)
    end
    @follower_count = Follow.where(followed_id: params[:id]).count
    @follow_count = Follow.where(user_id: params[:id]).count
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(
      name: params[:name], 
      email: params[:email], 
      password: params[:password]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザーを登録しました"
      redirect_to("/posts/index")
    else
      render("users/new")
    end
  end
  
  def login_form
    @email = ""
  end
  
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/posts/index")
    else 
      @email = params[:email]
      @err_msg = "メールアドレスまたはパスワードが正しくありません"
      render("users/login_form")
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end
  
  def search
    @search_results = User.where("name LIKE ?", "%#{params[:search_word]}%")
    @search_results_count = User.where("name LIKE ?", "%#{params[:search_word]}%").count
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col no-gutters p-0">
      <div class="jumbotron text-white mb-0" style="background:url(/photo_top2.jpg);background-size:cover;height:600%;background-position: center; ">
          
      </div>
    </div>
  </div>
</div>

app/views/home/top.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="col no-gutters p-0">
        <div class="carousel slide" id="c1" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#c1" data-slide-to="0" class="active"></li>
            <li data-target="#c1" data-slide-to="1" class=""></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item">
              <img src="/sky_top1.jpg" class="w-100 d-block">
            </div>
            <div class="carousel-item active">
              <img src="/photo_top2.jpg" class="w-100 d-block">
            </div>
          </div>
          <a href="#c1" class="carousel-control-prev" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
            <span class="sr-only">前の画像へ</span>
          </a>
          <a href="#c1" class="carousel-control-next" data-slide="next">
            <span class="carousel-control-next-icon"></span>
            <span class="sr-only">次の画像へ</span>
          </a>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" 
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    <title>TweetApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <% if @current_user %>
          <%= link_to("Tweet_sky", "/posts/index", {class: "navbar-brand"}) %>
        <% else %>
          <%= link_to("Tweet_sky", "/", {class: "navbar-brand"}) %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto flex-column flex-sm-row ">
            <% if @current_user %>
              <li class="nav-item mr-1">
                <%= link_to("ようこそ #{@current_user.name}さん", "/users/#{@current_user.id}", {class: "nav-link"}) %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to("ユーザー一覧", "/users/index", {class: "nav-link"}) %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to("投稿一覧", "/posts/index", {class: "nav-link"}) %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to("新規投稿", "/posts/new", {class: "nav-link"}) %>
              </li>
              <li class="nav-item mr-1">
                <%= form_tag("/users/search_result", method: :get, class: "nav-link") do %>
                  <input type="text" name="search_word" placeholder=" 検索" style="background-color:#343a40;border: solid 1px rgb(255 255 255 / 50%);color:white;">
                  <button type="submit" class="fas fa-search pt-1 pb-1" style="background-color:#343a40;color:rgb(255 255 255 / 50%);"></button>
                <% end %>
              </li>
              <li class="nav-item mr-2">
                <%= form_tag("/logout", method: :post, class: "nav-link") do %>
                <button type="submit" style="background-color:#343a40;color:rgb(255 255 255 / 50%);">ログアウト</button>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item mr-1">
                <%= link_to("Tweet_skyとは", "#", {class: "nav-link"}) %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to("新規登録", "/signup", {class: "nav-link"}) %>
              </li>
              <li class="nav-item mr-1">
                <%= link_to("ログイン", "/login", {class: "nav-link"}) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="alert-success d-flex justify-content-center align-items-center mb-1" style="height: 60px">
        <%= flash[:notice] %>
      </div>
    <% end %>
      <%= yield %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-8 mt-3 mb-3">
      <h1 class="text-black-50 text-left">編集する</h1>
    </div>
  </div>
  <% @post.errors.full_messages.each do |error_message| %>
  <div class="row justify-content-center">
    <div class="col-8">
      <ul class="list-unstyled alert-danger p-1 pl-3 mb-1">
        <li>
          <%= error_message %>
        </li>
      </ul>
    </div>
  </div>
  <% end %>
  <div class="row justify-content-center mt-3">
    <div class="col-8">
      <%= form_tag("/posts/#{@post.id}/update") do %>
      <div class="form-group mb-3">
        <textarea rows="6" class="form-control" name="content"><%= @post.content %></textarea>
      </div>
      <input class="btn btn-primary btn-block" type="submit" value="保存">
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-5 mt-3 mb-3">
      <h1 class="text-black-50 text-left">アカウント編集</h1>
    </div>
  </div>
  <% @user.errors.full_messages.each do |error_message| %>
  <div class="row justify-content-center">
    <div class="col-4">
      <ul class="list-unstyled alert-danger p-1 pl-2">
        <li>
          <%= error_message %>
        </li>
      </ul>
  </div>
  <% end %>
  <div class="row justify-content-center mt-3">
    <div class="col-4">
      <%= form_tag("/users/#{@user.id}/update", {multipart: true}) do %>
      <div class="form-group">
        <label for="user_name">ユーザー名</label>
        <input class="form-control mb-4" type="text" name="name" value="<%= @user.name %>" id="user_id">
        <label for="email">メールアドレス</label>
        <input class="form-control mb-4" type="text" name="email" value="<%= @user.email %>" id="email">
        <label for="image">プロフィール画像</label>
        <input class="mb-4" type="file" name="image" value="<%= @user.image_name %>" id="image">
        <label for="msg">ひとことメッセージ</label>
        <input class="form-control mb-4" type="text" name="self_intro" value="<%= @user.self_intro %>" placeholder="２０文字以内で入力してください" id="msg" row="2">
        <input class="btn btn-primary" type="submit" value="保存">
      </div>
      <% end %>
    </div>
  </div>
</div>
    <!--<#%= form_for @user,url: user_update_path do |u| %>-->
    <!--  <p>ユーザー名</p>-->
    <!--  <#%= u.text_field :name %>-->
    <!--  <p>メアド</p>-->
    <!--  <#%= u.text_field :email %>-->
    <!--  <#%= u.submit '保存' %>-->
    <!--<#% end %>-->

app/views/users/follows.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="jumbotron mb-0 text-white" style="background:url(/sky_profile.jpg);background-size:cover;height: 320px;">
        <div class="media">
          <% if @user.image_name %>
            <img src="<%= "/user_images/#{@user.image_name}" %>" style="max-width: 90px; height: auto;">
          <% else %>
            <span class="fas fa-user fa-9x" style="color: grey;background-color:#DDDDDD;"></span>
          <% end %>
          <div class="media-body ml-5">
            <h3 class="mb-3"><%= @user.name %></h3>
            <h6 class="mb-3"><%= @user.self_intro %></h6>
            <h6 class="mb-3"><%= @user.email %></h6>
            <% if @current_user.id == @user.id %>
            <div class="d-flex">
              <div><%= link_to("編集","/users/#{@user.id}/edit", {class: "text-white"}) %></div>
              <div>
                <h6 class="mt-1 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follower_count %></span> フォロワー</h6>
                <h6 class="mt-2 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follow_count %></span> フォロー</h6>
              </div>      
            </div>
            <% end %>
            <% if @current_user.id != @user.id %>
              <div class="mt-4 d-flex">
                <% if Follow.find_by(user_id: @current_user.id, followed_id: @user.id) %>
                  <%= button_to "フォロー中", follow_destroy_path, {method: :post, params: {id: @user.id}, class:"btn btn-primary"} %>
                <% else %>
                  <%= button_to "フォローする", follow_create_path, {method: :post, params: {id: @user.id}, class:"btn btn-secondary"} %>
                <% end %>
                <div>
                  <h6 class="mt-1 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follower_count %></span> フォロワー</h6>
                  <h6 class="mt-2 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follow_count %></span> フォロー</h6>
                </div>        
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-8">
      <nav class="navbar navbar-expand navbar-dark bg-primary">
        <ul class="navbar-nav w-100 nav-justified flex-column flex-sm-row">
          <li class="nav-item"><%= link_to("投稿", "/users/#{@user.id}", {class: "nav-link"}) %></li>
          <li class="nav-item"><%= link_to("いいね", "/users/#{@user.id}/likes", {class: "nav-link"}) %></li>
          <li class="nav-item active"><%= link_to("フォロー中", "/users/#{@user.id}/follows", {class: "nav-link"}) %></li>
        </ul>
      </nav>
    </div>
    <div class="col-8">
      <% if Follow.where(user_id: @user.id) && @posts %>
      <% @posts.each do |post| %>
        <% if post %>
        <div class="media border p-3">
          <% if post.user.image_name %>
            <img class="mr-3" src="<%= "/user_images/#{post.user.image_name}" %>" style="max-width: 40px; height: auto;">
          <% else %>
            <span class="fas fa-user fa-3x mr-3" style="color: grey;background-color:#DDDDDD;"></span>
          <% end %>
          <div class="media-body">
            <h6><%= link_to(post.user.name, "/users/#{post.user.id}") %></h6>
            <%= link_to(post.content, "/posts/#{post.id}", {class: "text-dark"}) %>
          </div>
        </div>
        <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="jumbotron mb-0 text-white" style="background:url(/sky_profile.jpg);background-size:cover;height: 320px;">
        <div class="media">
          <% if @user.image_name %>
            <img src="<%= "/user_images/#{@user.image_name}" %>" style="max-width: 90px; height: auto;">
          <% else %>
            <span class="fas fa-user fa-9x" style="color: grey;background-color:#DDDDDD;"></span>
          <% end %>
          <div class="media-body ml-5">
            <h3 class="mb-3"><%= @user.name %></h3>
            <h6 class="mb-3"><%= @user.self_intro %></h6>
            <h6 class="mb-3"><%= @user.email %></h6>
            <% if @current_user.id == @user.id %>
            <div class="d-flex">
              <div><%= link_to("編集","/users/#{@user.id}/edit", {class: "text-white"}) %></div>
              <div>
                <h6 class="mt-1 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follower_count %></span> フォロワー</h6>
                <h6 class="mt-2 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follow_count %></span> フォロー</h6>
              </div>      
            </div>
            <% end %>
            <% if @current_user.id != @user.id %>
              <div class="mt-4 d-flex">
                <% if Follow.find_by(user_id: @current_user.id, followed_id: @user.id) %>
                  <%= button_to "フォロー中", follow_destroy_path, {method: :post, params: {id: @user.id}, class:"btn btn-primary"} %>
                <% else %>
                  <%= button_to "フォローする", follow_create_path, {method: :post, params: {id: @user.id}, class:"btn btn-secondary"} %>
                <% end %>
                <div>
                  <h6 class="mt-1 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follower_count %></span> フォロワー</h6>
                  <h6 class="mt-2 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follow_count %></span> フォロー</h6>
                </div>        
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-8">
      <nav class="navbar navbar-expand navbar-dark bg-primary">
        <ul class="navbar-nav w-100 nav-justified flex-column flex-sm-row">
          <li class="nav-item"><%= link_to("投稿", "/users/#{@user.id}", {class: "nav-link"}) %></li>
          <li class="nav-item active"><%= link_to("いいね", "/users/#{@user.id}/likes", {class: "nav-link"}) %></li>
          <li class="nav-item"><%= link_to("フォロー中", "/users/#{@user.id}/follows", {class: "nav-link"}) %></li>
        </ul>
      </nav>
    </div>
    <div class="col-8">
        <% @likes.each do |like| %>
          <% post = Post.find_by(id: like.post_id) %>
          <% if post %>
          <div class="media border p-3">
            <% if post.user.image_name %>
              <img class="mr-3" src="<%= "/user_images/#{post.user.image_name}" %>" style="max-width: 40px; height: auto;">
            <% else %>
              <span class="fas fa-user fa-3x mr-3" style="color: grey;background-color:#DDDDDD;"></span>
            <% end %>
            <div class="media-body">
              <h6 class="mb-1 text-primary"><%= link_to(post.user.name, "/users/#{post.user_id}") %></h6>
              <%= link_to(post.content, "/posts/#{post.id}", {class: "text-dark"}) %>
            </div>
          </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="jumbotron mb-0 text-white" style="background:url(/sky_profile.jpg);background-size:cover;height: 320px;">
        <div class="media">
          <% if @user.image_name %>
            <img src="<%= "/user_images/#{@user.image_name}" %>" style="max-width: 90px; height: auto;">
          <% else %>
            <span class="fas fa-user fa-9x" style="color: grey;background-color:#DDDDDD;"></span>
          <% end %>
          <div class="media-body ml-5">
            <h3 class="mb-3"><%= @user.name %></h3>
            <h6 class="mb-3"><%= @user.self_intro %></h6>
            <h6 class="mb-3"><%= @user.email %></h6>
            <% if @current_user.id == @user.id %>
            <div class="d-flex">
              <div><%= link_to("編集","/users/#{@user.id}/edit", {class: "text-white"}) %></div>
              <div>
                <h6 class="mt-1 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follower_count %></span> フォロワー</h6>
                <h6 class="mt-2 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follow_count %></span> フォロー</h6>
              </div>      
            </div>
            <% end %>
            <% if @current_user.id != @user.id %>
              <div class="mt-4 d-flex">
                <% if Follow.find_by(user_id: @current_user.id, followed_id: @user.id) %>
                  <%= button_to "フォロー中", follow_destroy_path, {method: :post, params: {id: @user.id}, class:"btn btn-primary"} %>
                <% else %>
                  <%= button_to "フォローする", follow_create_path, {method: :post, params: {id: @user.id}, class:"btn btn-secondary"} %>
                <% end %>
                <div>
                  <h6 class="mt-1 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follower_count %></span> フォロワー</h6>
                  <h6 class="mt-2 ml-5 text-white-50"><span class="font-weight-bold text-white"><%= @follow_count %></span> フォロー</h6>
                </div>        
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-8">
      <nav class="navbar navbar-expand navbar-dark bg-primary">
        <ul class="navbar-nav w-100 nav-justified flex-column flex-sm-row">
          <li class="nav-item active"><%= link_to("投稿", "/users/#{@user.id}", {class: "nav-link"}) %></li>
          <li class="nav-item"><%= link_to("いいね", "/users/#{@user.id}/likes", {class: "nav-link"}) %></li>
          <li class="nav-item"><%= link_to("フォロー中", "/users/#{@user.id}/follows", {class: "nav-link"}) %></li>
        </ul>
      </nav>
    </div>
    <div class="col-8">
      <% @posts.each do |post| %>
      <% if post %>
        <div class="media border p-3">
          <% if post.user.image_name %>
            <img class="mr-3" src="<%= "/user_images/#{post.user.image_name}" %>" style="max-width: 40px; height: auto;">
          <% else %>
            <span class="fas fa-user fa-3x mr-3" style="color: grey;background-color:#DDDDDD;"></span>
          <% end %>
          <div class="media-body">
            <h6 class="mb-1 text-primary"><%= link_to(post.user.name, "/users/#{@user.id}") %></h6>
            <%= link_to(post.content, "/posts/#{post.id}", {class: "text-dark"}) %>
          </div>
        </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>